language: node_js
node_js:
    - "lts/*"
sudo: false
cache:
  directories:
    - $(npm config get cache)
install:
    - npm config set prefer-offline true
    - npm install -g enactjs/cli#develop
    - npm install

script:
    - npm run lint
    - npm run test
